### ISSUE TITLE
How to use the `state` extension.

### ISSUE THREAD

**Issue by John-Toohey** [prokopyl/clack#12]
I am developing a Clack host which needs to use the `state` extension to save/load plugin state. The problem is I cannot seem to acquire an owned `PluginMainThreadHandle`:

My code is as follows:

```rust
   let mut instance = // ...
   let mut settings: Vec<u8> = Vec::new();

    let host_main_thread = instance.main_thread_host_data_mut();
    let state = host_main_thread.state; // Option<PluginMainThreadHandle<'a>>
    if let Some(state) = state {
        let plugin_main_thread = host_main_thread.instance.as_mut().unwrap();
        state.load(plugin_main_thread, &mut settings.as_slice()); // ERROR: expected `PluginMainThreadHandle<'_>`, found `&mut PluginMainThreadHandle<'_>`
    } else {
        log::error!("Plugin does not support state!");
    }
``` 

Is it possible that the function is meant to take an `&mut PluginMainThreadHandle`, or am I missing something?

I greatly appreciate your work with this project, and look forward to your response.

**Comment by prokopyl** [comment]
Hi, and thanks for reporting this!

The state extension was indeed incorrectly implemented: extensions never need to take ownership of the plugin handles.

This has been fixed in the latest version. :slightly_smiling_face:
