### ISSUE TITLE
Port examples from clap-plugin

### ISSUE THREAD

**Issue by BenLeadbetter** [prokopyl/clack#13]
It would be great to port the example plugins from [clap-plugins](https://github.com/free-audio/clap-plugins) into clack. I'm not sure if such a project exists already, - I couldn't find anything linked from the clack docs or from a github search, so I'm guessing not(?)

Not sure yet whether it would be better to bind to the the C++ code already there via C ffi, or to entirely reimplement the targets in rust, loosely following the architecture from the original source.

**Comment by prokopyl** [comment]
Yes, I agree more examples for the plugin side of `clack` would be a good idea, and some of the examples from the clap-plugins repo are good candidates. :slightly_smiling_face: 

However, those examples are also meant to be examples for their own C++ wrapper, which differs quite a lot from the CLAP API, and therefore also from `clack`'s API. So I don't think it would make a lot of sense to follow their architecture at all (let alone binding to it using FFI).

Instead, I think it would be better to take what those examples do at a fundamental level (eg. a Gain plugin, a simple SVF filter, an ASDR envelope, a small synth, etc.), and implement them naturally using Clack, while focusing the code to show how to use a given set of features (e.g. audio I/O, parameter handling, MIDI input, state loading/saving, etc.).

**Comment by BenLeadbetter** [comment]
Do you know of any existing examples of clack instruments? I'm working g on a midi2 crate and I wanted to test it out by integrating it into an existing clack plugin.

**Comment by prokopyl** [comment]
There is an instrument example now as of #15 ! :slightly_smiling_face:
